source 'https://rubygems.org'

gem 'fluent-plugin-detect-exceptions', '~>0.0.11'
gem 'activesupport', '~>5.2.1'
gem 'fluent-plugin-elasticsearch'
gem 'ffi'
gem 'fluent-plugin-prometheus', '~>1.0.1'
gem 'fluent-plugin-rewrite-tag-filter', '~> 2.1.0'
gem "fluentd", "1.2.2"
gem 'oj', '~>3.6.5'
gem 'fluent-plugin-kubernetes_metadata_filter', '~> 2.1.4'
gem 'fluent-plugin-systemd', '~>1.0.1'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'fluent-plugin-concat', '~>2.3.0'
gem 'fluent-plugin-flowcounter', '~>1.3.0'
gem 'lru_redux'
gem 'rest-client', '~>2.0.2'


gem "git", "~>1.4.0"
gem "msgpack", "~>1.2.4"
gem "activesupport", "~>5.2.0"
# gem "fluent-plugin-kubernetes_metadata_filter", "~>1.0.0"
# gem "fluent-plugin-elasticsearch", "~>2.4.1"
# gem "fluent-plugin-systemd", "~>0.3.1"
# gem "fluent-plugin-detect-exceptions", "~>0.0.9"
# gem "fluent-plugin-prometheus", "~>0.3.0"
# gem "fluent-plugin-multi-format-parser", "~>1.0.0"
gem "oj"
gem "fluent-logger"
gem "fluent-mixin-config-placeholders"
gem "fluent-mixin-plaintextformatter"
gem "fluent-plugin-cadvisor"
gem "fluent-plugin-docker_metadata_filter"
gem "fluent-plugin-ignore-filter"
gem "fluent-plugin-kubernetes"
gem "fluent-plugin-mongo"
gem "fluent-plugin-record-reformer"
gem "fluent-plugin-rewrite-tag-filter"
gem "fluent-plugin-s3"
gem "fluent-plugin-scribe"
gem "fluent-plugin-secure-forward"
gem "fluent-plugin-snmp"
gem "fluent-plugin-td"
gem "fluent-plugin-td-monitoring"
gem "fluent-plugin-webhdfs"
gem "fluentd-ui", "1.0.0.alpha.2"
gem "sigdump"
gem "snmp"
gem "sprockets"
gem "sprockets-rails"
gem "sucker_punch"
gem "systemd-journal"
gem "systemu"
gem "td"
gem "td-client"
gem "td-logger"
gem "test-unit"
gem "thor"
gem "thread_safe"
gem "thrift"
gem "tilt"
gem "timers"
gem "tzinfo"
gem "tzinfo-data"
gem "unf"
gem "uuidtools"
gem "webhdfs"
gem "yajl-ruby"
gem "zip-zip"
gem "rails", "5.2.0"

# https://github.com/viaq/fluent-plugin-audit_log_parser
# https://github.com/shivaken/fluent-plugin-better-timestamp
# https://github.com/spynode/fluent-plugin-better-timestamp
# https://bitbucket.org/winebarrel/fluent-plugin-buffered-filter
# https://github.com/bwalex/fluent-plugin-docker-format
# https://github.com/okushchenko/fluent-plugin-docker-journald-concat
# https://github.com/fabric8io/fluent-plugin-docker_metadata_filter
# https://github.com/libresh/fluent-plugin-haproxy
# https://github.com/bungoume/fluent-plugin-ignore-filter
# https://github.com/One-com/fluent-plugin-journal-parser
# https://github.com/repeatedly/fluent-plugin-multi-format-parser
# https://github.com/activeshadow/fluent-plugin-split-event
# https://github.com/lingochamp/fluent-plugin-statsd
# https://github.com/mamewotoko/fluent-plugin-ufw
# https://github.com/tagomoris/fluent-plugin-growthforecast
# https://github.com/studio3104/fluent-plugin-graphite
# https://github.com/gumi/fluent-plugin-mysql-status
# https://github.com/robertpitt/fluent-plugin-nginx-status
# https://github.com/enukane/fluent-plugin-pcapng
# https://github.com/tagomoris/fluent-plugin-ping-message
# https://github.com/fakechris/fluent-plugin-statsd
# https://github.com/sowawa/fluent-plugin-slack
# https://github.com/fangli/fluent-plugin-influxdb
# https://github.com/fluent/fluent-plugin-mongo
# https://github.com/tagomoris/fluent-plugin-mysql
