{
 "title": "Prometheus Metrics in Influxdb - 6218",
 "description": "Show metrics in Influxdb as remote storage of Prometheus.  Data collector is Netdata. Applicable to monitoring system with Netdata+Prometheus+Influxdb+Grafana.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Load Average (load1)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"f64\") FROM \"_\" WHERE (\"__name__\" = 'netdata_system_load_load_average' AND \"dimension\"='load1' ) AND $timeFilter GROUP BY time(1m), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Average (load5)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"f64\") FROM \"_\" WHERE (\"__name__\" = 'netdata_system_load_load_average' AND \"dimension\"='load5' ) AND $timeFilter GROUP BY time(1m), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Average (load15)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"f64\") FROM \"_\" WHERE (\"__name__\" = 'netdata_system_load_load_average' AND \"dimension\"='load15' ) AND $timeFilter GROUP BY time(1m), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}