# https://gist.github.com/gnarf/b103e77f37236ca72d8e
# SOURCE: \cat roles/*/vagrant-config.yml | pbcopy
:vms:
  bosslab-master-01:
    :hostname: "bosslab-master-01"
    :ip: "192.168.20.101"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 10

  bosslab-worker-01:
    :hostname: "bosslab-worker-01"
    :ip: "192.168.20.102"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 11

  bosslab-worker-02:
    :hostname: "bosslab-worker-02"
    :ip: "192.168.20.103"
    :ram: 4096
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 11

  bosslab-proxy-01:
    :hostname: "bosslab-proxy-01"
    :ip: "192.168.20.104"
    :ram: 1024
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 11

###########################################################################
# ARM LAB START
###########################################################################
  # scarlett-cluster1:
  #   :hostname: "scarlett-cluster1"
  #   :ip: "192.168.33.100"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"

  # scarlett-cluster2:
  #   :hostname: "scarlett-cluster2"
  #   :ip: "192.168.33.101"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"

  # scarlett-cluster3:
  #   :hostname: "scarlett-cluster3"
  #   :ip: "192.168.33.102"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"

  # scarlett-cluster4:
  #   :hostname: "scarlett-cluster4"
  #   :ip: "192.168.33.103"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"

  # scarlett-ids:
  #   :hostname: "scarlett-ids"
  #   :ip: "192.168.33.104"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"

  # scarlett-office:
  #   :hostname: "scarlett-office"
  #   :ip: "192.168.33.105"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"

  # pine64:
  #   :hostname: "pine64"
  #   :ip: "192.168.33.106"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"

###########################################################################
# ARM LAB FINISH
###########################################################################
