---
- name: "prometheus-operator | Create directory: {{boss__prometheus__operator__manifest_path}}"
  file:
    path: "{{boss__prometheus__operator__manifest_path}}"
    state: directory

- name: "prometheus-operator | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__prometheus__operator__manifest_path }}/{{ item }}"
  with_items:
    - "00namespace-namespace.yaml"
    - "0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml"
    - "0prometheus-operator-0prometheusCustomResourceDefinition.yaml"
    - "0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml"
    - "0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml"
    - "0prometheus-operator-clusterRole.yaml"
    - "0prometheus-operator-clusterRoleBinding.yaml"
    - "0prometheus-operator-deployment.yaml"
    - "0prometheus-operator-pvc.yaml"
    - "0prometheus-operator-service.yaml"
    - "0prometheus-operator-serviceAccount.yaml"
    - "0prometheus-operator-serviceMonitor.yaml"
    - "alertmanager-alertmanager.yaml"
    - "alertmanager-ingress.yaml"
    - "alertmanager-secret.yaml"
    - "alertmanager-service.yaml"
    - "alertmanager-serviceAccount.yaml"
    - "alertmanager-serviceMonitor.yaml"
    - "grafana-config.yaml"
    - "grafana-dashboardDatasources.yaml"
    - "grafana-dashboardDefinitions.yaml"
    - "grafana-dashboardSources.yaml"
    - "grafana-deployment.yaml"
    - "grafana-ingress.yaml"
    - "grafana-service.yaml"
    - "grafana-serviceAccount.yaml"
    - "grafana-serviceMonitor.yaml"
    - "kube-state-metrics-clusterRole.yaml"
    - "kube-state-metrics-clusterRoleBinding.yaml"
    - "kube-state-metrics-deployment.yaml"
    - "kube-state-metrics-role.yaml"
    - "kube-state-metrics-roleBinding.yaml"
    - "kube-state-metrics-service.yaml"
    - "kube-state-metrics-serviceAccount.yaml"
    - "kube-state-metrics-serviceMonitor.yaml"
    - "node-exporter-clusterRole.yaml"
    - "node-exporter-clusterRoleBinding.yaml"
    - "node-exporter-daemonset.yaml"
    - "node-exporter-service.yaml"
    - "node-exporter-serviceAccount.yaml"
    - "node-exporter-serviceMonitor.yaml"
    - "prometheus-adapter-apiService.yaml"
    - "prometheus-adapter-clusterRole.yaml"
    - "prometheus-adapter-clusterRoleBinding.yaml"
    - "prometheus-adapter-clusterRoleBindingDelegator.yaml"
    - "prometheus-adapter-clusterRoleServerResources.yaml"
    - "prometheus-adapter-configMap.yaml"
    - "prometheus-adapter-deployment.yaml"
    - "prometheus-adapter-roleBindingAuthReader.yaml"
    - "prometheus-adapter-service.yaml"
    - "prometheus-adapter-serviceAccount.yaml"
    - "prometheus-clusterRole.yaml"
    - "prometheus-clusterRoleBinding.yaml"
    - "prometheus-ingress.yaml"
    - "prometheus-kubeControllerManagerPrometheusDiscoveryService.yaml"
    - "prometheus-kubeSchedulerPrometheusDiscoveryService.yaml"
    - "prometheus-prometheus.yaml"
    - "prometheus-roleBindingConfig.yaml"
    - "prometheus-roleBindingSpecificNamespaces.yaml"
    - "prometheus-roleConfig.yaml"
    - "prometheus-roleSpecificNamespaces.yaml"
    - "prometheus-rules.yaml"
    - "prometheus-service.yaml"
    - "prometheus-serviceAccount.yaml"
    - "prometheus-serviceMonitor.yaml"
    - "prometheus-serviceMonitorApiserver.yaml"
    - "prometheus-serviceMonitorCoreDNS.yaml"
    - "prometheus-serviceMonitorKubeControllerManager.yaml"
    - "prometheus-serviceMonitorKubeScheduler.yaml"
    - "prometheus-serviceMonitorKubelet.yaml"
    # - "additional-scrape-configs.yaml"
