---

- name: "unifi-exporter | Create directory: {{boss__unifi__exporter__manifest_path}}"
  file:
    path: "{{boss__unifi__exporter__manifest_path}}"
    state: directory

- name: "unifi-exporter | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__unifi__exporter__manifest_path }}/{{ item }}"
  with_items:
    - "unifi-exporter-deployment.yaml"
    - "unifi-exporter-secret-config.yaml"
    - "unifi-exporter-service.yaml"
    - "unifi-exporter-servicemonitor-router.yaml"


- name: kubectl create secret unifi-exporter-credentials and delete them so that we don't accidentally commit them
  shell: |
    kubectl --namespace={{boss__unifi__exporter__namespace_name}} create secret generic unifi-exporter-credentials --from-file={{ boss__unifi__exporter__manifest_path | expanduser }}/unifi-exporter-secret-config.yaml --dry-run -oyaml > {{ boss__unifi__exporter__manifest_path }}/unifi-exporter-credentials.yaml
    cat {{ boss__unifi__exporter__manifest_path }}/unifi-exporter-credentials.yaml
    rm {{ boss__unifi__exporter__manifest_path | expanduser }}/unifi-exporter-credentials.yaml
    rm {{ boss__unifi__exporter__manifest_path | expanduser }}/unifi-exporter-secret-config.yaml
  become: '{{ item }}'
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: "{{ k8_admin_config_path }}"
  with_items:
    - false  # Run as vagrant
