######################################################################################
# nfs - monitor w/ tmux
######################################################################################
- debug: msg="NFS Client - monitor tools"

- name: mkdir -p ~/.tmuxinator
  shell: |
    mkdir -p ~/.tmuxinator
  become: '{{ item }}'
  become_user: "{{bossjones__user}}"
  args:
    executable: /bin/bash
    creates: '$HOME/.tmuxinator'
  ignore_errors: yes
  with_items:
    - false  # Run as vagrant
  tags:
  - tmux
  - tmuxinator

- name: Generate /home/vagrant/.tmuxinator/perf.yaml file
  template:
    src: "home/vagrant/.tmuxinator/perf.yml.j2"
    dest: "/home/vagrant/.tmuxinator/perf.yml"
    mode: "0644"
  become: '{{ item }}'
  become_user: "{{bossjones__user}}"
  ignore_errors: yes
  with_items:
    - false  # Run as vagrant
  tags:
  - tmux
  - tmuxinator
