---
- src: geerlingguy.pip
- src: https://github.com/bossjones/ansible-goss-install
- src: https://github.com/bossjones/boss-ansible-role-bootstrap
- src: https://github.com/bossjones/boss-ansible-role-core
- src: https://github.com/bossjones/boss-ansible-role-graphite
- src: https://github.com/bossjones/boss-ansible-role-nfs
- src: https://github.com/bossjones/boss-ansible-role-ansible-workstation
- src: https://github.com/bossjones/boss-ansible-role-wireshark
- src: https://github.com/bossjones/boss-ansible-role-sysctl
- src: https://github.com/bossjones/boss-ansible-role-dnsmasq
- src: https://github.com/bossjones/boss-ansible-role-dhcpd
- src: https://github.com/bossjones/boss-ansible-role-dhclient
- src: https://github.com/bossjones/boss-ansible-role-locales
- src: https://github.com/bossjones/boss-ansible-role-secret
- src: https://github.com/bossjones/boss-ansible-role-pki
- src: https://github.com/bossjones/boss-ansible-role-apt_install
- src: https://github.com/bossjones/boss-ansible-role-apt
- src: https://github.com/bossjones/boss-ansible-role-java
- src: https://github.com/bossjones/boss-ansible-role-netdata
- src: https://github.com/bossjones/boss-ansible-role-maven
- src: https://github.com/bossjones/boss-ansible-role-users
- src: https://github.com/bossjones/boss-ansible-role-debug
- src: https://github.com/bossjones/boss-ansible-role-docker
- src: https://github.com/bossjones/boss-ansible-role-rsyslogd
- src: https://github.com/bossjones/boss-ansible-role-environment
- src: https://github.com/bossjones/boss-ansible-role-etckeeper
- src: https://github.com/bossjones/boss-ansible-role-fact
- src: https://github.com/bossjones/boss-ansible-role-journald
- src: https://github.com/bossjones/boss-ansible-role-ntp
- src: https://github.com/bossjones/boss-ansible-role-timezone
- src: https://github.com/bossjones/boss-ansible-role-tools
- src: https://github.com/bossjones/boss-ansible-role-update-hosts
- src: https://www.github.com/mrlesmithjr/ansible-logrotate
- src: https://www.github.com/mrlesmithjr/ansible-motd
- src: https://www.github.com/mrlesmithjr/ansible-netdata.git
- src: https://www.github.com/mrlesmithjr/ansible-nginx.git
- src: https://www.github.com/mrlesmithjr/ansible-ntp.git
- src: https://www.github.com/mrlesmithjr/ansible-timezone.git
- src: https://www.github.com/mrlesmithjr/ansible-influxdb.git
- src: rvm.ruby
