---
- name: "metallb | Create directory: {{boss__metallb__manifest_path}}"
  file:
    path: "{{boss__metallb__manifest_path}}"
    state: directory

- name: "metallb | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__metallb__manifest_path }}/{{ item }}"
  with_items:
    - "00metallb_kube.yaml"
    - "metallb-config.yaml"
