version: "3.0"
services:
  rsyslogcentral:
    network_mode: host
    image: bossjones/rsyslog:0.1.0
    # volumes:
    #   - ./kapacitor:/opt/kapacitor
    #   - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    #   - /tmp/example.sock:/tmp/example.sock
    # environment:
      # - KAPACITOR_LOAD_ENABLED=true
      # - KAPACITOR_LOAD_DIR=/opt/kapacitor
      # - USE_VALGRIND=off
