---

- name: "fluentd-centralized | Create directory: {{boss__fluentd__centralized__manifest_path}}"
  file:
    path: "{{boss__fluentd__centralized__manifest_path}}"
    state: directory

- name: "fluentd-centralized | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__fluentd__centralized__manifest_path }}/{{ item }}"
  with_items:
    - "0fluentd-centralized.namespace.yaml"
    - "1fluentd-centralized-service-account.yaml"
    - "2fluentd-centralized-role.yaml"
    - "3fluentd-centralized-role-binding.yaml"
    - "4fluentd-centralized-configmap{{boss__fluentd__centralized__configmap_suffix}}.yaml"
    # - "4fluentd-centralized-configmap.yaml"
    - "5fluentd-centralized.deploy.yaml"
    - "6fluentd-centralized.svc.yaml"
    - "7fluentd-centralized.ingress.yaml"

- name: Clean artifact path
  file:
    state: "{{boss__fluentd__centralized__create_namespace}}"
    path: "{{ boss__fluentd__centralized__manifest_path }}/0fluentd-centralized.namespace.yaml"
  when: boss__fluentd__centralized__create_namespace is defined and boss__fluentd__centralized__create_namespace == "absent"


- name: Clean artifact path ingress
  file:
    state: "{{boss__fluentd__centralized__create_ingress}}"
    path: "{{ boss__fluentd__centralized__manifest_path }}/7fluentd-centralized.ingress.yaml"
  when: boss__fluentd__centralized__create_ingress is defined and boss__fluentd__centralized__create_ingress == "absent"
