---
- name: Converge
  hosts: all
  # gather_facts: True
  roles:
    - role: boss-ansible-role-debug

      boss__debug__debug_variables_file: '/tmp/ansible_variables'
      boss__debug__dump_dir: '/etc/ansible_dumps'
      boss__debug__dump_type: 'unified' # seperate

      # bossjones__user: vagrant
      # bossjones__group: vagrant

