---

- name: "calico | Create directory: {{boss__calico__manifest_path}}"
  file:
    path: "{{boss__calico__manifest_path}}"
    state: directory

- name: "calico | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__calico__manifest_path }}/{{ item }}"
  with_items:
    - "calico.yaml"
    - "rbac-kdd.yaml"
