---

# htpasswd -Bbn admin admin123 | base64

- name: "registry | Create httpasswd: htpasswd -Bbn admin admin123"

  shell: |
    htpasswd -Bbn admin admin123 | tee htpasswd.base64
  # args:
  #   creates: 'htpasswd.base64'
  register: boss__registry__htpasswd_base64_results

- name: "registry | debug fact boss__registry__htpasswd_base64_results"
  debug: msg="{{boss__registry__htpasswd_base64_results}}"

- name: "registry | set base64 fact"
  set_fact:
    htpasswd_base64: '{{boss__registry__htpasswd_base64_results.stdout | b64encode }}'

- name: "registry | Create directory: {{boss__registry__manifest_path}}"
  file:
    path: "{{boss__registry__manifest_path}}"
    state: directory

- name: "registry | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__registry__manifest_path }}/{{ item }}"
  with_items:
    - "registry-ingress.yml"
    - "registry-ns.yml"
    - "0registry-pvc.yml"
    - "registry-rs.yml"
    - "registry-svc.yml"
    - "registry-svc-statefulset.yml"
    - "99registry-cert-tls.yml"
