---
- name: "prometheus-operator-custom | Create directory: {{boss__prometheus__operator__custom__manifest_path}}"
  file:
    path: "{{boss__prometheus__operator__custom__manifest_path}}"
    state: directory

- name: "prometheus-operator-custom | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__prometheus__operator__custom__manifest_path }}/{{ item }}"
  with_items: []
