---
- name: "efk | Create directory: {{boss__efk__manifest_path}}"
  file:
    path: "{{boss__efk__manifest_path}}"
    state: directory

- name: "efk | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__efk__manifest_path }}/{{ item }}"
  with_items:
    - "0elasticsearch-pvc.yaml"
    - "0elasticsearch.service-account.yaml"
    - "1elasticsearch.cluster-role.yaml"
    - "2elasticsearch.role-binding.yaml"
    - "elasticsearch-statefulset.yaml"
    - "elasticsearch-service.yaml"
    - "elasticsearch-ingress.yaml"
    - "elasticsearch-curator-secret.yaml"
    - "elasticsearch-curator.yaml"
    - "fluentd-es-configmap.yaml"
    - "fluentd-es-ds.yaml"
    - "kibana-deployment.yaml"
    - "kibana-ingress.yaml"
    - "kibana-service.yaml"
