---
- name: "helm | Create directory: {{boss__helm__manifest_path}}"
  file:
    path: "{{boss__helm__manifest_path}}"
    state: directory

- name: "helm | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__helm__manifest_path }}/{{ item }}"
  with_items:
    - "00helm_tiller_rbac.yaml"
