---
- name: "ingress-nginx | Create directory: {{boss__ingress__nginx__manifest_path}}"
  file:
    path: "{{boss__ingress__nginx__manifest_path}}"
    state: directory

- name: "ingress-nginx | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__ingress__nginx__manifest_path }}/{{ item }}"
  with_items:
    - "ingress-configmap.yaml"
    - "ingress-dp.yaml"
    - "ingress-rbac.yaml"
    - "ingress-svc-nodeport.yaml"
    - "ingress-svc.yaml"
