---

- name: "certmanager | Create directory: {{boss__certmanager__manifest_path}}"
  file:
    path: "{{boss__certmanager__manifest_path}}"
    state: directory

- name: "certmanager | Write manifests (RBAC)"
  template:
    src: "{{ item }}.j2"
    dest: "{{ boss__certmanager__manifest_path }}/{{ item }}"
  with_items:
    - "cert-manager.yaml"
    - "cert-self-signed.yaml"
    - "generate-cluster-issuer-ca.sh"


############## now run script to create secrets then upload them

- name: kubectl create secret unifi-exporter-credentials and delete them so that we don't accidentally commit them
  shell: |
    bash {{ boss__certmanager__manifest_path }}/generate-cluster-issuer-ca.sh

    ls -lta {{ boss__certmanager__manifest_path }}
  become: '{{ item }}'
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: "{{ k8_admin_config_path }}"
  with_items:
    - false  # Run as vagrant
  when: boss__certmanager__my_cluster_generate_tls is defined and boss__certmanager__my_cluster_generate_tls == "force"


# kubectl create secret tls my-cluster-ca-key-pair --cert={{ boss__certmanager__manifest_path | expanduser }}/ca.crt \
# --key={{ boss__certmanager__manifest_path | expanduser }}/ca.key \
# --namespace={{boss__certmanager__my_cluster_namespace_name}}
